name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - 'arm64'
        - 'x86-64'
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup mkosi
      uses: systemd/mkosi@v16

    - name: Summary
      run: |
        sudo mkosi summary

    - name: Build Image
      run: |
        sudo mkosi --architecture=${{ matrix.architecture }}

    - name: Upload Image
      uses: actions/upload-artifact@v3
      with:
        name: fedora-image-${{ matrix.architecture }}
        path: ./
