name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup mkosi
      uses: systemd/mkosi@v16
  
    - name: Summary
      run: |
        sudo mkosi summary

    - name: Build Image
      run: |
        sudo mkosi

    - name: Upload Image
      uses: actions/upload-artifact@v3
      with:
        name: fedora-image
        path: image.raw
