name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        python3 -m pip install --user git+https://github.com/systemd/mkosi.git@v16

    - run: find $HOME -name mkosi

    - name: Build
      run: |
        MKOSI=/home/runner/.local/lib/mkosi
        $MKOSI --help

    - name: Build
      run: |
        $MKOSI --version
