name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install mkosi
      run: |
        sudo apt-get update
        sudo apt-get install -y bubblewrap
        python3 -m pip install --upgrade setuptools wheel pip
        python3 -m venv testvenv
        testvenv/bin/python3 -m pip install --upgrade setuptools wheel pip
        testvenv/bin/python3 -m pip install git+https://github.com/systemd/mkosi.git@v16
        testvenv/bin/mkosi -h
        testvenv/bin/mkosi --version
        testvenv/bin/mkosi build --help

    - name: Build
      run: |
        MKOSI=$PWD/testvenv/bin/mkosi
        sudo $MKOSI --debug --directory=$PWD

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: image.raw
