name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        python3 -m pip --user install git+https://github.com/systemd/mkosi.git@v16

    - name: Build
      run: |
        MKOSI=/home/runner/.local/lib/mkosi
        sudo $MKOSI --help

    - name: Build
      run: |
        sudo $MKOSI --version
